import type { Metadata } from 'next'
import ThemeRegistry from '../../theme/ThemeRegistry'
import NextAuthProvider from '@/context/SessionProviderContext'
import Navbar from '@/components/nav'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <ThemeRegistry>
        <body>
          <NextAuthProvider>
            <Navbar />
            {children}
          </NextAuthProvider>
        </body>
      </ThemeRegistry>
    </html>
  )
}
